# Generated by Django 5.2.4 on 2026-07-08 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_animal_usuario_rebaño_usuario_registroordeno_usuario_and_more'),
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('TRIAL', 'Prueba (Trial)'), ('BASIC', 'Básico'), ('PREMIUM', 'Premium')], default='TRIAL', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('SUSPENDIDA', 'Suspendida')], default='ACTIVA', max_length=20)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_saas', to='app1.user')),
            ],
        ),
    ]
