# Generated by Django 5.2.4 on 2026-07-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_suscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='plan',
            field=models.CharField(choices=[('TRIAL', 'Prueba (Trial)'), ('BASICO', 'Básico'), ('PLUS', 'Plus'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], default='TRIAL', max_length=20),
        ),
    ]
