# Generated by Django 5.2.4 on 2026-09-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_suscripcion_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: BASICO, PLUS, PREMIUM', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('badge', models.CharField(default='Popular', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('limite_fincas', models.IntegerField(default=1)),
                ('limite_animales', models.IntegerField(default=100)),
                ('caracteristicas_list', models.TextField(blank=True, help_text='Separadas por salto de línea', null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='monto_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='LogSistemaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SISTEMA', 'Sistema'), ('FINANZAS', 'Finanzas'), ('CLIENTES', 'Clientes'), ('PLANES', 'Planes')], max_length=50)),
                ('descripcion', models.TextField()),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.user_admin')),
            ],
        ),
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('periodo_correspondiente', models.CharField(help_text='Ej: Septiembre 2026', max_length=50)),
                ('estado', models.CharField(choices=[('AL_DIA', 'Al Día'), ('PENDIENTE', 'Pendiente / Debe'), ('RECHAZADO', 'Rechazado')], default='AL_DIA', max_length=20)),
                ('comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.user_admin')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app2.suscripcion')),
            ],
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.plansaas'),
        ),
    ]
