# Generated by Django 5.2.4 on 2026-09-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_plansaas_suscripcion_monto_mensual_logsistemaadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansaas',
            name='mod_auditoria',
            field=models.BooleanField(default=True, verbose_name='Módulo de Auditoría'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='mod_crianza',
            field=models.BooleanField(default=True, verbose_name='Módulo de Crianza'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='mod_empleados',
            field=models.BooleanField(default=True, verbose_name='Módulo de Empleados'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='mod_engorde',
            field=models.BooleanField(default=True, verbose_name='Módulo de Engorde'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='mod_estructura_costos',
            field=models.BooleanField(default=True, verbose_name='Módulo de Estructura de Costos'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='mod_finanzas',
            field=models.BooleanField(default=True, verbose_name='Módulo de Finanzas'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='mod_genetica',
            field=models.BooleanField(default=True, verbose_name='Módulo de Genética'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='mod_incidentes',
            field=models.BooleanField(default=True, verbose_name='Módulo de Incidentes'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='mod_inventario',
            field=models.BooleanField(default=True, verbose_name='Módulo de Inventario'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='mod_potreros',
            field=models.BooleanField(default=True, verbose_name='Módulo de Potreros'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='mod_reproduccion',
            field=models.BooleanField(default=True, verbose_name='Módulo de Reproducción'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='mod_vacunacion',
            field=models.BooleanField(default=True, verbose_name='Módulo de Vacunación'),
        ),
    ]
