# Generated by Django 5.2.4 on 2026-09-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_plansaas_mod_auditoria_plansaas_mod_crianza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansaas',
            name='mod_ordeno',
            field=models.BooleanField(default=True, verbose_name='Módulo de Ordeño'),
        ),
    ]
