# Generated by Django 5.2.4 on 2026-09-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_plansaas_mod_ordeno'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default='Eres Veti, un asistente de inteligencia artificial especializado en ganadería bovina. Trabajas dentro de Samanito, un sistema de gestión ganadera. Puedes ayudar con temas de manejo animal, reproducción, sanidad, nutrición, registros zootécnicos, finanzas de finca, ordeño, engorde y todo lo relacionado con la producción bovina. Responde siempre en español, de forma clara, profesional y amigable. Si el usuario hace preguntas no relacionadas con ganadería, puedes responderlas brevemente pero recuérdale tu especialidad.', help_text='Instrucciones base que definen el comportamiento de Veti.', verbose_name='Prompt del sistema')),
                ('modelo', models.CharField(default='deepseek-chat', help_text='Nombre del modelo a usar (ej: deepseek-chat, deepseek-reasoner).', max_length=60, verbose_name='Modelo DeepSeek')),
                ('temperatura', models.FloatField(default=0.7, help_text='Controla la creatividad. 0 = preciso, 2 = muy creativo.', verbose_name='Temperatura (0.0 – 2.0)')),
                ('max_tokens', models.IntegerField(default=1024, help_text='Límite de longitud de cada respuesta.', verbose_name='Máx. tokens de respuesta')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, el asistente no estará disponible para los usuarios.', verbose_name='Veti habilitado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Veti',
            },
        ),
    ]
