# Generated by Django 5.2.4 on 2026-10-01 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_veticonfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Binance Pay, Banesco, Zelle...', max_length=100)),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria Nacional'), ('ZELLE', 'Zelle'), ('BINANCE', 'Binance Pay'), ('PAGO_MOVIL', 'Pago Móvil'), ('OTRO', 'Otro Método')], default='TRANSFERENCIA', max_length=50)),
                ('titular', models.CharField(blank=True, max_length=150, null=True)),
                ('identificacion', models.CharField(blank=True, help_text='Cédula, RUC, o ID de Binance', max_length=100, null=True)),
                ('numero_cuenta_o_correo', models.CharField(help_text='Número de cuenta, teléfono o correo', max_length=150)),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones adicionales para el usuario al pagar', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pagosuscripcion',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='pagosuscripcion',
            name='estado',
            field=models.CharField(choices=[('AL_DIA', 'Aprobado / Al Día'), ('PENDIENTE', 'Pendiente / En Revisión'), ('RECHAZADO', 'Rechazado')], default='AL_DIA', max_length=20),
        ),
        migrations.AddField(
            model_name='pagosuscripcion',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_recibidos', to='app2.metodopago'),
        ),
    ]
