# Generated by Django 5.2.4 on 2026-10-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_metodopago_alter_pagosuscripcion_comprobante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='numero_cuenta_o_correo',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='titular',
        ),
        migrations.AddField(
            model_name='metodopago',
            name='campos_personalizados',
            field=models.JSONField(default=dict, help_text='Campos dinámicos del método de pago'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='region',
            field=models.CharField(default='Global', help_text='Ej: Venezuela, Colombia, Global...', max_length=100),
        ),
    ]
