# Generated by Django 5.2.4 on 2026-10-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_remove_metodopago_identificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='tipo',
        ),
    ]
