# Generated by Django 5.2.4 on 2026-10-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_remove_metodopago_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosuscripcion',
            name='meses_pagados',
            field=models.IntegerField(default=1, help_text='Cantidad de meses que cubre este pago'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='descuento_12_meses',
            field=models.IntegerField(default=0, help_text='Descuento en porcentaje'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='descuento_3_meses',
            field=models.IntegerField(default=0, help_text='Descuento en porcentaje (ej. 10 para 10%)'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='descuento_6_meses',
            field=models.IntegerField(default=0, help_text='Descuento en porcentaje'),
        ),
    ]
