# Generated by Django 5.2.4 on 2026-10-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_pagosuscripcion_meses_pagados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansaas',
            name='mod_chat_ia',
            field=models.BooleanField(default=True, verbose_name='Módulo de Asistente IA (Veti)'),
        ),
    ]
