# Generated by Django 5.2.4 on 2026-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('bloqueado', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
