# Generated by Django 5.2.4 on 2026-07-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rebaño_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='estado_reproductivo',
            field=models.CharField(choices=[('NINGUNO', 'Ninguno / No Aplica'), ('VACIA', 'Vacía'), ('PREÑADA', 'Preñada'), ('EN_ESPERA', 'En Espera de Parto')], default='NINGUNO', max_length=20),
        ),
        migrations.AddField(
            model_name='rebaño',
            name='es_dinamico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rebaño',
            name='filtro_avanzado',
            field=models.CharField(blank=True, choices=[('ORDENO', 'Vacas en Ordeño (con cría < 1 año)'), ('HORRO', 'Vacas Horras (Preñadas o sin cría)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rebaño',
            name='filtro_edad_max_meses',
            field=models.IntegerField(blank=True, help_text='Edad máxima en meses', null=True),
        ),
        migrations.AddField(
            model_name='rebaño',
            name='filtro_edad_min_meses',
            field=models.IntegerField(blank=True, help_text='Edad mínima en meses', null=True),
        ),
        migrations.AddField(
            model_name='rebaño',
            name='filtro_sexo',
            field=models.CharField(blank=True, choices=[('M', 'Solo Machos'), ('H', 'Solo Hembras')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='rebaño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales_fijos', to='app1.rebaño'),
        ),
    ]
