# Generated by Django 5.2.4 on 2026-07-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_animal_estado_reproductivo_rebaño_es_dinamico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='estado_reproductivo',
        ),
        migrations.RemoveField(
            model_name='rebaño',
            name='filtro_avanzado',
        ),
        migrations.AddField(
            model_name='animal',
            name='estado_gestacion',
            field=models.CharField(choices=[('VACIA', 'Vacía'), ('PREÑADA', 'Preñada'), ('N_A', 'No Aplica')], default='N_A', max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='estado_produccion',
            field=models.CharField(choices=[('LACTANCIA', 'En Lactancia'), ('SECA', 'Seca / Horra'), ('N_A', 'No Aplica')], default='N_A', max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='uso_macho',
            field=models.CharField(choices=[('REPRODUCTOR', 'Reproductor'), ('ENGORDE', 'Engorde'), ('N_A', 'No Aplica')], default='N_A', max_length=20),
        ),
        migrations.AddField(
            model_name='rebaño',
            name='filtro_estado_gestacion',
            field=models.CharField(blank=True, choices=[('VACIA', 'Vacía'), ('PREÑADA', 'Preñada')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rebaño',
            name='filtro_estado_produccion',
            field=models.CharField(blank=True, choices=[('LACTANCIA', 'En Lactancia'), ('SECA', 'Seca / Horra')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rebaño',
            name='filtro_uso_macho',
            field=models.CharField(blank=True, choices=[('REPRODUCTOR', 'Reproductor'), ('ENGORDE', 'Engorde')], max_length=20, null=True),
        ),
    ]
