# Generated by Django 5.2.4 on 2026-07-05 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_animal_estado_reproductivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroOrdeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_finalizacion', models.TimeField()),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('rebaño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ordeno', to='app1.rebaño')),
            ],
        ),
    ]
