# Generated by Django 5.2.4 on 2026-07-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_registroordeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='destetado',
            field=models.BooleanField(default=False, help_text='Indica si el animal ya fue destetado'),
        ),
    ]
