# Generated by Django 5.2.4 on 2026-07-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_animal_destetado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usar_mamanto', models.BooleanField(default=True)),
                ('usar_destete', models.BooleanField(default=True)),
                ('meses_mamanto', models.IntegerField(default=3)),
                ('meses_destete', models.IntegerField(default=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='app1.user')),
            ],
        ),
    ]
