# Generated by Django 5.2.4 on 2026-07-05 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_configuracionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
        migrations.AddField(
            model_name='rebaño',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
        migrations.AddField(
            model_name='registroordeno',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
