# Generated by Django 5.2.4 on 2026-07-08 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_animal_usuario_rebaño_usuario_registroordeno_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='app1.user')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.finca'),
        ),
        migrations.AddField(
            model_name='rebaño',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.finca'),
        ),
        migrations.AddField(
            model_name='registroordeno',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.finca'),
        ),
    ]
