# Generated by Django 5.2.4 on 2026-07-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_finca_animal_finca_rebaño_finca_registroordeno_finca'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='propietario',
            field=models.CharField(blank=True, help_text='Propietario del animal', max_length=150, null=True),
        ),
    ]
