# Generated by Django 5.2.4 on 2026-07-09 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='estado_vida',
            field=models.CharField(choices=[('VIVO', 'En Finca'), ('VENDIDO', 'Vendido'), ('FALLECIDO', 'Fallecido')], default='VIVO', max_length=20),
        ),
        migrations.CreateModel(
            name='VentaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('CRIA', 'Para Cría / Vida'), ('SACRIFICIO', 'Para Sacrificio (Kilos)')], max_length=20)),
                ('kilos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comprador', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venta_info', to='app1.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
