# Generated by Django 5.2.4 on 2026-07-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_animal_estado_vida_ventaanimal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaanimal',
            name='animal',
        ),
        migrations.AddField(
            model_name='ventaanimal',
            name='animales',
            field=models.ManyToManyField(related_name='ventas_info', to='app1.animal'),
        ),
    ]
