# Generated by Django 5.2.4 on 2026-08-17 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_incidentesanitario_planvacunacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('ALIMENTO', 'Alimento / Suplementos'), ('VETERINARIA', 'Medicina / Veterinaria'), ('PERSONAL', 'Sueldos / Personal'), ('SERVICIOS', 'Servicios Públicos (Luz, Agua)'), ('MANTENIMIENTO', 'Mantenimiento / Infraestructura'), ('OTRO', 'Otros Gastos')], max_length=50)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('FIJO', 'Gasto Fijo'), ('VARIABLE', 'Gasto Variable')], default='VARIABLE', max_length=20)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioLecheConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_por_litro', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('finca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precio_leche_config', to='app1.finca')),
            ],
        ),
    ]
