# Generated by Django 5.2.4 on 2026-08-17 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_gastofinca_preciolecheconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('CREACION', 'Creación / Registro'), ('MODIFICACION', 'Modificación / Actualización'), ('ELIMINACION', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('IMPORTACION', 'Importación Masiva'), ('CONFIGURACION', 'Cambio de Configuración')], max_length=50)),
                ('modulo', models.CharField(choices=[('ANIMALES', 'Animales'), ('REBAÑOS', 'Rebaños'), ('ORDEÑO', 'Control de Ordeño'), ('SANIDAD', 'Sanidad'), ('VENTAS', 'Ventas'), ('FINANZAS', 'Finanzas'), ('SEGURIDAD', 'Seguridad / Acceso')], max_length=50)),
                ('descripcion', models.TextField()),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
