# Generated by Django 5.2.4 on 2026-08-17 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_logactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(default=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrales', to='app1.finca')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='corral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='app1.corral'),
        ),
        migrations.CreateModel(
            name='HistorialTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='app1.animal')),
                ('corral_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_destino', to='app1.corral')),
                ('corral_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_origen', to='app1.corral')),
            ],
        ),
        migrations.CreateModel(
            name='PesajeAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesajes', to='app1.animal')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_alimento', models.CharField(max_length=150)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('corral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentaciones', to='app1.corral')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentaciones', to='app1.finca')),
            ],
        ),
        migrations.CreateModel(
            name='TareaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('ALIMENTACION', 'Alimentación'), ('SANIDAD', 'Sanidad'), ('LIMPIEZA', 'Limpieza / Mantenimiento'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('completada', models.BooleanField(default=False)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='app1.finca')),
            ],
        ),
    ]
