# Generated by Django 5.2.4 on 2026-08-17 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_corral_animal_corral_historialtransferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='caravana_electronica',
            field=models.CharField(blank=True, help_text='RFID / Caravana Electrónica', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='estado_salud',
            field=models.CharField(choices=[('SANO', 'Sano'), ('TRATAMIENTO', 'En Tratamiento'), ('HOSPITAL', 'Hospitalizado / Aislado')], default='SANO', max_length=20),
        ),
        migrations.AddField(
            model_name='corral',
            name='es_hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProtocoloTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('diagnostico_asociado', models.CharField(help_text='Diagnóstico por defecto', max_length=200)),
                ('medicamento', models.CharField(help_text='Medicamento sugerido', max_length=200)),
                ('dosis', models.CharField(help_text='Dosis recomendada, ej: 10ml, 1 tableta', max_length=100)),
                ('duracion_dias', models.IntegerField(default=3, help_text='Duración en días')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='app1.finca')),
            ],
        ),
    ]
