# Generated by Django 5.2.4 on 2026-08-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_animal_caravana_electronica_animal_estado_salud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaComedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntuacion', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], help_text='Puntuación de 0 a 4 (0: vacío, 4: intacto)')),
                ('ajuste_sugerido_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Ajuste automático calculado', max_digits=5)),
                ('corral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_comederos', to='app1.corral')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCargaMixer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('capacidad_mixer_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('viajes_json', models.TextField(help_text='Detalles de viajes e ingredientes por viaje en formato JSON')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_mixer', to='app1.finca')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ingredientes_json', models.TextField(help_text="Ingredientes y proporciones en formato JSON, ej: [{'nombre': 'Maíz', 'porcentaje': 60, 'costo_por_kg': 0.15}]")),
                ('racion_base_kg', models.DecimalField(decimal_places=2, default=5.0, help_text='Ración diaria base por animal', max_digits=6)),
                ('dias_transicion', models.IntegerField(default=10, help_text='Días de transición para incrementos')),
                ('incremento_porcentaje', models.DecimalField(decimal_places=2, default=5.0, help_text='Porcentaje de incremento sugerido por transición', max_digits=5)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos_alimentacion', to='app1.finca')),
            ],
        ),
    ]
