# Generated by Django 5.2.4 on 2026-08-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_lecturacomedero_ordencargamixer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactividad',
            name='modulo',
            field=models.CharField(choices=[('ANIMALES', 'Animales'), ('REBAÑOS', 'Rebaños'), ('SANIDAD', 'Sanidad'), ('VENTAS', 'Ventas'), ('FINANZAS', 'Finanzas'), ('SEGURIDAD', 'Seguridad / Acceso')], max_length=50),
        ),
        migrations.DeleteModel(
            name='RegistroOrdeno',
        ),
    ]
