# Generated by Django 5.2.4 on 2026-08-27 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_logactividad_modulo_delete_registroordeno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('MEDICAMENTO', 'Medicamentos / Vacunas'), ('ALIMENTO', 'Alimentos / Suplementos'), ('HERRAMIENTA', 'Herramientas / Equipos'), ('OTRO', 'Otros')], default='OTRO', max_length=50)),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('LT', 'Litros'), ('UNIDAD', 'Unidades'), ('DOSIS', 'Dosis')], default='UNIDAD', max_length=20)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('alerta_minimo', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_inventario', to='app1.finca')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoGestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(choices=[('PALPACION', 'Palpación Rectal'), ('ECOGRAFIA', 'Ecografía')], default='PALPACION', max_length=20)),
                ('resultado', models.CharField(choices=[('PREÑADA', 'Preñada'), ('VACIA', 'Vacía')], default='PREÑADA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
                ('hembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_gestacion', to='app1.animal')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada / Compra'), ('SALIDA', 'Salida / Consumo'), ('AJUSTE', 'Ajuste')], default='SALIDA', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app1.articuloinventario')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user')),
            ],
        ),
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hectareas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_pasto', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(choices=[('DESCANSO', 'En Descanso'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DESCANSO', max_length=20)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potreros', to='app1.finca')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('PARTO', 'Parto Normal'), ('ABORTO', 'Aborto')], default='PARTO', max_length=20)),
                ('facilidad', models.CharField(choices=[('NORMAL', 'Normal / Sin Ayuda'), ('ASISTIDO', 'Asistido / Distocia'), ('N_A', 'No Aplica')], default='NORMAL', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parto_origen', to='app1.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos_registrados', to='app1.animal')),
            ],
        ),
        migrations.CreateModel(
            name='RotacionPotrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
                ('potrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones', to='app1.potrero')),
                ('rebaño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones_potrero', to='app1.rebaño')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioReproductivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MONTA', 'Monta Natural'), ('IA', 'Inseminación Artificial'), ('TE', 'Transferencia Embriones')], default='MONTA', max_length=20)),
                ('fecha', models.DateField()),
                ('toro_o_pajilla', models.CharField(help_text='ID del toro o lote de pajilla', max_length=150)),
                ('fecha_probable_parto', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
                ('hembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_reproductivos', to='app1.animal')),
            ],
        ),
    ]
