# Generated by Django 5.2.4 on 2026-08-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_articuloinventario_diagnosticogestacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='composicion_racial',
            field=models.CharField(blank=True, help_text='Ej: 5/8 Holstein, 3/8 Gyr', max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='CatalogoSemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_toro', models.CharField(max_length=150)),
                ('raza', models.CharField(max_length=100)),
                ('codigo_pajilla', models.CharField(max_length=50, unique=True)),
                ('pta_leche', models.DecimalField(blank=True, decimal_places=2, help_text='Predicted Transmitting Ability', max_digits=6, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(choices=[('MAYORAL', 'Mayoral'), ('VETERINARIO', 'Veterinario'), ('OBRERO', 'Obrero / Peón')], max_length=50)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_contratacion', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='app1.finca')),
            ],
        ),
        migrations.AddField(
            model_name='tareadiaria',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to='app1.empleado'),
        ),
        migrations.CreateModel(
            name='PagoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(help_text='Ej: Quincena 1 Enero', max_length=200)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app1.empleado')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user')),
            ],
        ),
    ]
