# Generated by Django 5.2.4 on 2026-09-16 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_animal_composicion_racial_catalogosemen_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potrero',
            name='rebaño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potreros_asignados', to='app1.rebaño'),
        ),
    ]
