# Generated by Django 5.2.4 on 2026-09-20 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_potrero_rebaño'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('ALIMENTO', 'Alimento / Suplementos'), ('VETERINARIA', 'Medicina / Veterinaria'), ('PERSONAL', 'Sueldos / Personal'), ('SERVICIOS', 'Servicios Públicos (Luz, Agua)'), ('MANTENIMIENTO', 'Mantenimiento / Infraestructura'), ('OTRO', 'Otros Gastos')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frecuencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
