# Generated by Django 5.2.4 on 2026-09-20 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_gastorecurrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentesanitario',
            name='articulo_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_sanitarios', to='app1.articuloinventario'),
        ),
        migrations.AddField(
            model_name='incidentesanitario',
            name='cantidad_utilizada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad de medicamento usada', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo total de la entrada / compra', max_digits=12),
        ),
        migrations.AddField(
            model_name='planvacunacion',
            name='articulo_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunaciones', to='app1.articuloinventario'),
        ),
        migrations.AddField(
            model_name='planvacunacion',
            name='dosis_por_animal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dosis por animal administrado', max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='LiquidacionLeche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('litros_totales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_por_litro', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprador', models.CharField(blank=True, help_text='Cliente / Receptor de la leche', max_length=150, null=True)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente de Cobro'), ('COBRADO', 'Cobrado')], default='PENDIENTE', max_length=20)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.finca')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
