# Generated by Django 5.2.4 on 2026-09-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_webauthncredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionusuario',
            name='animales_por_pag',
            field=models.IntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=25, help_text='Filas por página en tablas de animales'),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='formato_fecha',
            field=models.CharField(choices=[('DMY', 'DD/MM/YYYY'), ('MDY', 'MM/DD/YYYY'), ('YMD', 'YYYY-MM-DD')], default='DMY', max_length=3),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='moneda_simbolo',
            field=models.CharField(default='$', help_text='Símbolo de moneda, ej: $, Bs, €', max_length=5),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='mostrar_codigo',
            field=models.BooleanField(default=True, help_text='Mostrar código del animal en tablas (si False, muestra el nombre)'),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='notif_partos',
            field=models.BooleanField(default=True, help_text='Alertas de partos próximos (vacas preñadas)'),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='notif_vacunas',
            field=models.BooleanField(default=True, help_text='Recordatorios de vacunaciones pendientes'),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='notif_vencimientos',
            field=models.BooleanField(default=True, help_text='Alertas de suscripción próxima a vencer'),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='tema_preferido',
            field=models.CharField(choices=[('CLARO', 'Claro'), ('OSCURO', 'Oscuro'), ('AUTO', 'Automático (sistema)')], default='CLARO', max_length=6),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='unidad_peso',
            field=models.CharField(choices=[('KG', 'Kilogramos (kg)'), ('LB', 'Libras (lb)')], default='KG', max_length=2),
        ),
    ]
