# Generated by Django 5.2.4 on 2026-09-28 23:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_configuracionusuario_animales_por_pag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroOrdeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('turno', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche'), ('DIARIO', 'Diario / Consolidado')], default='MAÑANA', max_length=20)),
                ('vacas_ordenadas', models.IntegerField(default=1, help_text='Cantidad de vacas ordenadas en el turno/día')),
                ('litros_leche', models.DecimalField(decimal_places=2, help_text='Litros totales de leche', max_digits=10)),
                ('precio_litro', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio por litro al momento del registro', max_digits=8)),
                ('temperatura_tanque', models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura °C del tanque de enfriamiento', max_digits=4, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, help_text='Animal individual si el registro es por vaca', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_ordeno_animal', to='app1.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ordeno', to='app1.finca')),
                ('rebaño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_ordeno', to='app1.rebaño')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
