# Generated by Django 5.2.4 on 2026-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_registroordeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentesanitario',
            name='estado',
            field=models.CharField(choices=[('ATENDIENDO', 'En Atendiendo'), ('RECUPERACION', 'En Recuperación'), ('RECUPERADO', 'Recuperado / Resuelto')], default='ATENDIENDO', max_length=20),
        ),
    ]
